### ISSUE TITLE
Missing code to create file 'fb15k_tail_norm_vector.pickle'

### ISSUE THREAD

**Issue by IceIce1ce** [wangmengsd/RSME#3]
Hi authors, thanks for your paper as well as your code. However, when I open MRP.py file, I don't see any code to create file 'fb15k_tail_norm_vector.pickle'. I wonder how we can get this file.

**Comment by vandarkfan** [comment]
> 

I have the same problem. Have you solved it

**Comment by IceIce1ce** [comment]
still not yet.
